project:
  type: website
  output-dir: docs

website:
  title: "Pulling Threads"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rdinnager
      - icon: twitter
        href: https://twitter.com/ecologician
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

